/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mdshop;


import java.sql.Connection; 
import java.sql.DriverManager; 

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement; 
import java.text.DecimalFormat;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DANNY
 */
public final class Main extends javax.swing.JFrame {

    public Connection con;
    
    public Main() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("MDShop POS");
        
        getConnection();
    }
public void getConnection() {
        String JDBC_DRIVER = "com.mysql.jdbc.Driver";
        String URL = "jdbc:mysql://localhost:3306/POSDatabase";
        String USERNAME = "root";
        String PASSWORD = "root";
        try {
            Class.forName(JDBC_DRIVER);
            con = DriverManager.getConnection(URL, USERNAME, PASSWORD);
        } catch (ClassNotFoundException | SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("posdatabase?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        productsQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery.getResultList();
        customersQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Customers c");
        customersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : customersQuery.getResultList();
        customersQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Customers c");
        customersList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : customersQuery1.getResultList();
        employeesQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Employees e");
        employeesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : employeesQuery.getResultList();
        productsQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery1.getResultList();
        productsQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery2.getResultList();
        productsQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery3.getResultList();
        productsQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery4.getResultList();
        productsQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery5.getResultList();
        productsQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery6.getResultList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jTextFieldProductCode = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSelectedProduct = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelDiscount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelNet = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonTotal = new javax.swing.JButton();
        jButtonStartSale1 = new javax.swing.JButton();
        jButtonLogOff = new javax.swing.JButton();
        jButtonStock = new javax.swing.JButton();
        jButtonStaff = new javax.swing.JButton();
        jButtonCustomer = new javax.swing.JButton();
        jLabelSaleNo = new javax.swing.JLabel();
        jCheckBoxDiscount = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productsList6, jTableProducts);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productId}"));
        columnBinding.setColumnName("Product Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productName}"));
        columnBinding.setColumnName("Product Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productColor}"));
        columnBinding.setColumnName("Product Color");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productSize}"));
        columnBinding.setColumnName("Product Size");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productDescription}"));
        columnBinding.setColumnName("Product Description");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productQuantity}"));
        columnBinding.setColumnName("Product Quantity");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productPrice}"));
        columnBinding.setColumnName("Product Price");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jTableProducts);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 50, 1112, 238);

        jTextFieldProductCode.setEnabled(false);
        jTextFieldProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductCodeActionPerformed(evt);
            }
        });
        jTextFieldProductCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProductCodeKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldProductCode);
        jTextFieldProductCode.setBounds(10, 10, 260, 28);

        jTableSelectedProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSelectedProduct.setEnabled(false);
        jTableSelectedProduct.setRowSelectionAllowed(false);
        jTableSelectedProduct.getTableHeader().setReorderingAllowed(false);
        jTableSelectedProduct.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTableSelectedProduct);
        if (jTableSelectedProduct.getColumnModel().getColumnCount() > 0) {
            jTableSelectedProduct.getColumnModel().getColumn(0).setResizable(false);
            jTableSelectedProduct.getColumnModel().getColumn(1).setResizable(false);
            jTableSelectedProduct.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 294, 684, 352);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TOTAL         :");

        jLabelDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDiscount.setText("0 %");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("DISCOUNT :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("NET              : ");

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabelTotal.setText("...");

        jLabelNet.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabelNet.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jLabelNet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTotal))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDiscount))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNet))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(694, 294, 423, 350);

        jButtonTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTotal.setText("TOTAL");
        jButtonTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonTotalMouseReleased(evt);
            }
        });
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });

        jButtonStartSale1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonStartSale1.setText("START SALE");
        jButtonStartSale1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartSale1ActionPerformed(evt);
            }
        });

        jButtonLogOff.setBackground(new java.awt.Color(204, 0, 0));
        jButtonLogOff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogOff.setText("LOG OFF");
        jButtonLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOffActionPerformed(evt);
            }
        });

        jButtonStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonStock.setText("STOCK");
        jButtonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStockActionPerformed(evt);
            }
        });

        jButtonStaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonStaff.setText("STAFF");
        jButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffActionPerformed(evt);
            }
        });

        jButtonCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCustomer.setText("CUSTOMER");
        jButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogOff, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jButtonStartSale1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jButtonStock, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jButtonStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonStartSale1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButtonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStock, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(1122, 50, 252, 662);

        jLabelSaleNo.setText("SALE NO. ");
        getContentPane().add(jLabelSaleNo);
        jLabelSaleNo.setBounds(400, 20, 101, 14);

        jCheckBoxDiscount.setText("DISCOUNT");
        jCheckBoxDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDiscountActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxDiscount);
        jCheckBoxDiscount.setBounds(0, 660, 140, 23);

        jLabelName.setText("...");
        getContentPane().add(jLabelName);
        jLabelName.setBounds(1210, 10, 140, 14);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1382, 807));
    }// </editor-fold>//GEN-END:initComponents

 
    
    
    
    private void jButtonLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOffActionPerformed
       this.dispose();
        login lg = new login() ;
       lg.setVisible(true);
    }//GEN-LAST:event_jButtonLogOffActionPerformed

    private void jButtonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStockActionPerformed
       this.dispose();
        stock stock = new stock() ;
       stock.setVisible(true);
    }//GEN-LAST:event_jButtonStockActionPerformed

    private void jTextFieldProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeActionPerformed
try{
  
    
            
        getConnection(); 
        Statement st = con.createStatement();
        String query = "SELECT product_id,product_name,product_price FROM products WHERE product_id LIKE '%" + jTextFieldProductCode.getText() + "%'";
      ResultSet rs = st.executeQuery(query);
      jTableSelectedProduct.setModel(DbUtils.resultSetToTableModel(rs)); 
  
    
    
    con.close();
            
    }

     catch (SQLException | NumberFormatException e) { 
        JOptionPane.showMessageDialog(null,"ITEM DOES NOT EXIST");
        System.err.println(e.getMessage()); 
               
    }//GEN-LAST:event_jTextFieldProductCodeActionPerformed

    
    
    
    
    
    
     int total = 0;
        
        if (jCheckBoxDiscount.isSelected()) {
         for (int i = 0; i < jTableSelectedProduct.getRowCount(); i++){
        int amount = Integer.parseInt((String) jTableSelectedProduct.getValueAt(i, 2));
        total += amount  ;
       
        jLabelTotal.setText(String.valueOf(total)); 
         jLabelNet.setText(String.valueOf(total-(total*30)/100));
         
         
               
        }
       
        }
         
        else{
           for (int i = 0; i < jTableSelectedProduct.getRowCount(); i++){
        int amount = Integer.parseInt((String) jTableSelectedProduct.getValueAt(i, 2));
        total += amount  ;
       
        jLabelTotal.setText(String.valueOf(total)); 
         jLabelNet.setText(String.valueOf(total)); 
         
        }
        }  
    
    
    
    
    
    
    
    }
    private void jTextFieldProductCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductCodeKeyReleased
    
       
    }//GEN-LAST:event_jTextFieldProductCodeKeyReleased

    private void jButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffActionPerformed
this.dispose();
        employee employee = new employee() ;
       employee.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStaffActionPerformed

    private void jButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerActionPerformed
        
        customer customer = new customer() ;
       customer.setVisible(true);        
    }//GEN-LAST:event_jButtonCustomerActionPerformed

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        
        
       
       
    }//GEN-LAST:event_jButtonTotalActionPerformed
    
    private void jCheckBoxDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDiscountActionPerformed
      if (jCheckBoxDiscount.isSelected()) {
        jLabelDiscount.setText("30 %");
      }else{
          
        jLabelDiscount.setText("0 %");
    }
    }//GEN-LAST:event_jCheckBoxDiscountActionPerformed

    private void jButtonTotalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTotalMouseReleased
       transaction transaction = new transaction() ;
       transaction.setVisible(true);
       transaction.jLabelTotal.setText(jLabelNet.getText());
    }//GEN-LAST:event_jButtonTotalMouseReleased

    private void jButtonStartSale1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartSale1ActionPerformed
       jTextFieldProductCode.setEnabled(true);
    }//GEN-LAST:event_jButtonStartSale1ActionPerformed
        
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<mdshop.Customers> customersList;
    private java.util.List<mdshop.Customers> customersList1;
    private javax.persistence.Query customersQuery;
    private javax.persistence.Query customersQuery1;
    private java.util.List<mdshop.Employees> employeesList;
    private javax.persistence.Query employeesQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButtonCustomer;
    private javax.swing.JButton jButtonLogOff;
    private javax.swing.JButton jButtonStaff;
    private javax.swing.JButton jButtonStartSale1;
    private javax.swing.JButton jButtonStock;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JCheckBox jCheckBoxDiscount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDiscount;
    public static final javax.swing.JLabel jLabelName = new javax.swing.JLabel();
    private javax.swing.JLabel jLabelNet;
    javax.swing.JLabel jLabelSaleNo;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProducts;
    private javax.swing.JTable jTableSelectedProduct;
    private javax.swing.JTextField jTextFieldProductCode;
    private java.util.List<mdshop.Products> productsList;
    private java.util.List<mdshop.Products> productsList1;
    private java.util.List<mdshop.Products> productsList2;
    private java.util.List<mdshop.Products> productsList3;
    private java.util.List<mdshop.Products> productsList4;
    private java.util.List<mdshop.Products> productsList5;
    private java.util.List<mdshop.Products> productsList6;
    private javax.persistence.Query productsQuery;
    private javax.persistence.Query productsQuery1;
    private javax.persistence.Query productsQuery2;
    private javax.persistence.Query productsQuery3;
    private javax.persistence.Query productsQuery4;
    private javax.persistence.Query productsQuery5;
    private javax.persistence.Query productsQuery6;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
